{% set version = "4.23.0.20250516" %}

package:
  name: types-jsonschema
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-jsonschema/types_jsonschema-{{ version }}.tar.gz
    sha256: 9ace09d9d35c4390a7251ccd7d833b92ccc189d24d1b347f26212afce361117e
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - referencing

test:
  commands:
    - pip check
    - test -f $SP_DIR/jsonschema-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\jsonschema-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for jsonschema
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/mypy
